<?php

return [
    'sections' => [
        'operational' => [
            'label' => 'Operasional',
            'rows' => [
                ['pos' => '4100000000', 'description' => 'Pendapatan Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_income'],
                ['pos' => '4101010100', 'description' => 'i. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010201', 'description' => 'Giro', 'coas' => ['401'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010202', 'description' => 'Tabungan', 'coas' => ['402'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010203', 'description' => 'Deposito', 'coas' => ['403', '407'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010204', 'description' => 'Sertifikat Deposito', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010301', 'description' => 'Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010302', 'description' => 'Kepada Pihak Ketiga bukan Bank', 'coas' => ['411', '413'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101020100', 'description' => 'i. Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101020200', 'description' => 'ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['421', '422'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030100', 'description' => 'i. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030201', 'description' => 'Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030202', 'description' => 'Kepada Pihak Ketiga bukan Bank', 'coas' => ['427'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101040000', 'description' => 'd. Koreksi Atas Pendapatan Bunga -/-', 'coas' => ['428', '429'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102010000', 'description' => 'a Pendapatan Jasa Transaksi', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102020000', 'description' => 'b Keuntungan Penjualan Valuta Asing', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102030000', 'description' => 'c Keuntungan Penjualan Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102040000', 'description' => 'd Penerimaan Kredit yang Dihapusbuku', 'coas' => ['426'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102050000', 'description' => 'e Pemulihan CKPN', 'coas' => ['435'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102060000', 'description' => 'f Dividen', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102070000', 'description' => 'g Keuntungan dari penyertaan dengan equity method', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4201020000', 'description' => 'h Keuntungan penjualan AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4203000000', 'description' => 'i Pendapatan Ganti Rugi Asuransi', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4202020000', 'description' => 'j Pemulihan penurunan nilai AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102990000', 'description' => 'k Lainnya', 'coas' => ['412', '423', '424', '425', '431', '432', '433', '434', '440', '490'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '5100000000', 'description' => 'Beban Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_expense'],
                ['pos' => '5101010100', 'description' => 'i. Tabungan', 'coas' => ['5012101', '5012102', '5012103', '5012104', '5012105', '5012106', '5012107', '5012108', '5012109', '5012110', '5012112', '5012113', '5012114', '5012115', '5012199'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010200', 'description' => 'ii. Deposito', 'coas' => ['5022200', '5022201'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010300', 'description' => 'iii. Simpanan dari Bank Lain', 'coas' => ['5012111', '5012116', '5022202', '5022203', '592'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010401', 'description' => '1) Dari Bank Indonesia', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010402', 'description' => '2) Dari Bank Lain', 'coas' => ['511'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010403', 'description' => '3) Dari Pihak Ketiga Bukan Bank', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010404', 'description' => '4) Berupa Pinjaman Subordinasi', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101019900', 'description' => 'v. Lainnya', 'coas' => ['517', '512', '513', '529', '593'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101020100', 'description' => 'i. Kepada Bank Lain', 'coas' => ['514', '516', '591'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101020200', 'description' => 'ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['518'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5102000000', 'description' => '2 Beban Kerugian Restrukturisasi Kredit', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103010000', 'description' => 'a. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103020000', 'description' => 'b. Penempatan pada Bank Lain', 'coas' => ['531'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103030100', 'description' => 'i. Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103030200', 'description' => 'ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['521'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103050000', 'description' => 'e Aset Keuangan Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5104000000', 'description' => '4 Beban Pemasaran', 'coas' => ['567'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5105000000', 'description' => '5 Beban Penelitian dan Pengembangan', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106010100', 'description' => 'i. Gaji dan Upah', 'coas' => ['551', '553'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106010200', 'description' => 'ii. Honorarium', 'coas' => ['552'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106019900', 'description' => 'iii. Lainnya', 'coas' => ['554', '555', '556', '557'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106020000', 'description' => 'b Beban Pendidikan dan Pelatihan', 'coas' => ['542', '543'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106030100', 'description' => 'i. Gedung Kantor', 'coas' => ['564'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106039900', 'description' => 'ii. Lainnya', 'coas' => ['565', '566'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106040000', 'description' => 'd Beban Penyusutan/Penghapusan atas Aset Tetap dan Inventaris', 'coas' => ['533', '534'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106050000', 'description' => 'e Beban Amortisasi Aset Tidak Berwujud', 'coas' => ['532', '577'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106060000', 'description' => 'f Beban Premi Asuransi', 'coas' => ['574', '575', '576', '515'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106070000', 'description' => 'g Beban Pemeliharaan dan Perbaikan', 'coas' => ['571', '572', '573'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106080000', 'description' => 'h Beban Barang dan Jasa', 'coas' => ['594', '561', '562', '563', '568'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106100000', 'description' => 'i Beban Penyelenggaraan Teknologi Informasi', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106110100', 'description' => 'a. Kecurangan internal', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106110200', 'description' => 'b. Kejahatan eksternal', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106090000', 'description' => 'k Pajak-pajak', 'coas' => ['578', '558'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199010000', 'description' => 'a Kerugian Penjualan Valuta Asing', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199020000', 'description' => 'b Kerugian Penjualan Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199030000', 'description' => 'c Kerugian dari penyertaan dengan equity method', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5201020000', 'description' => 'd Kerugian penjualan AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5202020000', 'description' => 'e Kerugian penurunan nilai AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199990000', 'description' => 'f Lainnya', 'coas' => ['599', '541', '544', '545', '546', '547', '559', '569', '580'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '3104040100', 'description' => 'Laba (Rugi) Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_profit'],
            ],
        ],
        'non_operational' => [
            'label' => 'Non Operasional',
            'rows' => [
                ['pos' => '4200000000', 'description' => 'Pendapatan Non Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_income'],
                ['pos' => '4201010000', 'description' => 'a Aset Tetap dan Inventaris', 'coas' => ['601', '602', '603'], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4202010000', 'description' => 'a Aset Tetap dan Inventaris', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4202030000', 'description' => 'b Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4204000000', 'description' => '3 Bunga Antar Kantor', 'coas' => ['604'], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4205000000', 'description' => '4 Selilsih Kurs', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4299000000', 'description' => '5 Lainnya', 'coas' => ['690'], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '5200000000', 'description' => 'Beban Non Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_expense'],
                ['pos' => '5201010000', 'description' => 'a Aset Tetap dan Inventaris', 'coas' => ['701', '702', '703'], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5202010000', 'description' => 'a Aset Tetap dan Inventaris', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5202030000', 'description' => 'b Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5203000000', 'description' => '3 Bunga Antar Kantor', 'coas' => ['704'], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5204000000', 'description' => '4 Selisih Kurs', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5299000000', 'description' => '5 Lainnya', 'coas' => ['790'], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '3104040200', 'description' => 'Laba (Rugi) Non Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_profit'],
                ['pos' => '3104040300', 'description' => 'Laba (Rugi) Tahun Berjalan Sebelum Pajak', 'coas' => [], 'is_total' => true, 'formula' => 'profit_before_tax'],
            ],
        ],
        'tax_and_comprehensive' => [
            'label' => 'Pajak & Komprehensif',
            'rows' => [
                ['pos' => '5300000000', 'description' => 'Taksiran Pajak Penghasilan', 'coas' => ['312'], 'is_total' => false, 'group' => 'tax_expense'],
                ['pos' => '4400000000', 'description' => 'Pendapatan Pajak Tangguhan', 'coas' => [], 'is_total' => false, 'group' => 'deferred_tax_income'],
                ['pos' => '5400000000', 'description' => 'Beban Pajak Tangguhan', 'coas' => ['558'], 'is_total' => false, 'group' => 'deferred_tax_expense'],
                ['pos' => '3104040400', 'description' => 'Jumlah Laba (Rugi) Tahun Berjalan', 'coas' => [], 'is_total' => true, 'formula' => 'current_year_profit'],
                ['pos' => '7101010000', 'description' => 'a. Keuntungan Revaluasi Aset Tetap', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7101990000', 'description' => 'b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7101980000', 'description' => 'c. Pajak Penghasilan terkait', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102010000', 'description' => 'a. Keuntungan (Kerugian) dan Perubahan Nilai Aset Keuangan Dalam Kelompok Tersedia untuk Dijual', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102990000', 'description' => 'b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102980000', 'description' => 'c. Pajak Penghasilan terkait', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '3104040500', 'description' => 'Penghasilan Komprehensif Lain Setelah Pajak', 'coas' => [], 'is_total' => true, 'formula' => 'other_comprehensive_income'],
                ['pos' => '3104040600', 'description' => 'Total Laba (Rugi) Komprehensif Tahun Berjalan', 'coas' => [], 'is_total' => true, 'formula' => 'comprehensive_profit'],
            ],
        ],
    ],
];
