<?php

return [
    'sections' => [
        'operational' => [
            'label' => 'Operasional',
            'rows' => [
                ['pos' => '4100000000', 'description' => 'Pendapatan Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_income'],

                ['pos' => '', 'description' => '    1. Pendapatan Bunga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '', 'description' => '        a. Bunga Kontraktual', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010100', 'description' => '            i. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '', 'description' => '            ii. Penempatan pada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010201', 'description' => '                Giro', 'coas' => ['401'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010202', 'description' => '                Tabungan', 'coas' => ['402'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010203', 'description' => '                Deposito', 'coas' => ['403', '407'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010204', 'description' => '                Sertifikat Deposito', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '', 'description' => '            iii. Kredit yang Diberikan', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010301', 'description' => '                Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101010302', 'description' => '                Kepada Pihak Ketiga Bukan Bank', 'coas' => ['411', '413'], 'is_total' => false, 'group' => 'operating_income'],

                ['pos' => '', 'description' => '        b. Provisi Kredit', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101020100', 'description' => '            i. Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101020200', 'description' => '            ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['421'], 'is_total' => false, 'group' => 'operating_income'],

                ['pos' => '', 'description' => '        c. Biaya Transaksi -/-', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030100', 'description' => '            i. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '', 'description' => '            ii. Kredit yang Diberikan', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030201', 'description' => '                Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101030202', 'description' => '                Kepada Pihak Ketiga Bukan Bank', 'coas' => ['427'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4101040000', 'description' => '        d. Koreksi atas Pendapatan Bunga -/-', 'coas' => ['428'], 'is_total' => false, 'group' => 'operating_income'],

                ['pos' => '', 'description' => '    2. Pendapatan Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102010000', 'description' => '        a. Pendapatan Jasa Transaksi', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102020000', 'description' => '        b. Keuntungan Penjualan Valuta Asing', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102030000', 'description' => '        c. Keuntungan Penjualan Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102040000', 'description' => '        d. Penerimaan Aset Produktif yang Dihapus Buku', 'coas' => ['426'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102050000', 'description' => '        e. Pemulihan Cadangan Kerugian Penurunan Nilai', 'coas' => ['435'], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102060000', 'description' => '        f. Dividen', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102070000', 'description' => '        g. Keuntungan dari penyertaan equity method', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4201020000', 'description' => '        h. Keuntungan penjualan AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4203000000', 'description' => '        i. Pendapatan ganti rugi asuransi', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4202020000', 'description' => '        j. Pemulihan penurunan nilai AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_income'],
                ['pos' => '4102990000', 'description' => '        k. Lainnya', 'coas' => ['412', '422', '423', '424', '425', '429', '431', '432', '433', '434', '440', '490'], 'is_total' => false, 'group' => 'operating_income'],

                ['pos' => '5100000000', 'description' => 'Beban Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_expense'],

                ['pos' => '', 'description' => '    1. Beban Bunga', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '', 'description' => '        a. Beban Bunga Kontraktual', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010100', 'description' => '            i. Tabungan', 'coas' => ['5012101', '5012102', '5012103', '5012104', '5012105', '5012106', '5012107', '5012108', '5012109', '5012110', '5012112', '5012113', '5012114', '5012115', '5012199'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010200', 'description' => '            ii. Deposito', 'coas' => ['5022200', '5022201'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010300', 'description' => '            iii. Simpanan dari Bank Lain', 'coas' => ['5012111', '5012116', '5022202', '5022203'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '', 'description' => '            iv. Pinjaman yang Diterima', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010401', 'description' => '                1) Dari Bank Indonesia', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010402', 'description' => '                2) Dari Bank Lain', 'coas' => ['511', '512'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010403', 'description' => '                3) Dari Pihak Ketiga Bukan Bank', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101010404', 'description' => '                4) Berupa Pinjaman Subordinasi', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101019900', 'description' => '            v. Lainnya', 'coas' => ['517', '529', '593'], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '', 'description' => '        b. Biaya Transaksi', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101020100', 'description' => '            i. Kepada Bank Lain', 'coas' => ['513', '514', '516'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5101020200', 'description' => '            ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['518'], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '5102000000', 'description' => '    2. Beban Kerugian Restrukturisasi Kredit', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '', 'description' => '    3. Beban Kerugian Penurunan Nilai', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103010000', 'description' => '        a. Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103020000', 'description' => '        b. Penempatan pada Bank Lain', 'coas' => ['531'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '', 'description' => '        c. Kredit yang Diberikan', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103030100', 'description' => '            i. Kepada Bank Lain', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103030200', 'description' => '            ii. Kepada Pihak Ketiga Bukan Bank', 'coas' => ['521'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5103050000', 'description' => '        e. Aset Keuangan Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '5104000000', 'description' => '    4. Beban Pemasaran', 'coas' => ['567'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5105000000', 'description' => '    5. Beban Penelitian dan Pengembangan', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '', 'description' => '    6. Beban Administrasi dan Umum', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '', 'description' => '        a. Beban Tenaga Kerja', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106010100', 'description' => '            i. Gaji dan Upah', 'coas' => ['551'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106010200', 'description' => '            ii. Honorarium', 'coas' => ['552', '553'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106019900', 'description' => '            iii. Lainnya', 'coas' => ['554', '555'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106020000', 'description' => '        b. Beban Pendidikan dan Pelatihan', 'coas' => ['542', '543'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '', 'description' => '        c. Beban Sewa', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106030100', 'description' => '            i. Gedung Kantor', 'coas' => ['532', '5641000'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106039900', 'description' => '            ii. Lainnya', 'coas' => ['534', '5641001', '565', '566'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106040000', 'description' => '        d. Beban Penyusutan/Penghapusan atas Aset Tetap dan Inventaris', 'coas' => ['5331000', '5331001', '5331002', '5331003', '5331004', '5331005', '5331006', '5331008', '5331009'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106050000', 'description' => '        e. Beban Amortisasi Aset Tidak Berwujud', 'coas' => ['5331007', '577'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106060000', 'description' => '        f. Beban Premi Asuransi', 'coas' => ['556', '557', '574', '575', '576', '515'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106070000', 'description' => '        g. Beban Pemeliharaan dan Perbaikan', 'coas' => ['571', '572', '573'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106080000', 'description' => '        h. Beban Barang dan Jasa', 'coas' => ['541', '544', '545', '546', '547', '559', '594', '561', '562', '563', '568', '591'], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106100000', 'description' => '        i. Beban Penyelenggaraan Teknologi Informasi', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106110000', 'description' => '        j. Kerugian terkait Risiko Operasional', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106111000', 'description' => '            i. Kecurangan internal', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106112000', 'description' => '            ii. Kejahatan eksternal', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5106090000', 'description' => '        k. Pajak-Pajak', 'coas' => ['578'], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '', 'description' => '    7. Beban Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199010000', 'description' => '        a. Kerugian Penjualan Valuta Asing', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199020000', 'description' => '        b. Kerugian Penjualan Surat Berharga', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199030000', 'description' => '        c. Kerugian dari penyertaan dengan Equity Method', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5201020000', 'description' => '        d. Kerugian penjualan AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5202020000', 'description' => '        e. Kerugian penurunan nilai AYDA', 'coas' => [], 'is_total' => false, 'group' => 'operating_expense'],
                ['pos' => '5199990000', 'description' => '        f. Lainnya', 'coas' => ['599', '569'], 'is_total' => false, 'group' => 'operating_expense'],

                ['pos' => '3104040100', 'description' => 'Laba (Rugi) Operasional', 'coas' => [], 'is_total' => true, 'formula' => 'operating_profit'],
            ],
        ],

        'non_operational' => [
            'label' => 'Nonoperasional',
            'rows' => [
                ['pos' => '4200000000', 'description' => 'Pendapatan Nonoperasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_income'],
                ['pos' => '', 'description' => '    1. Keuntungan Penjualan', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4201010000', 'description' => '        Aset Tetap dan Inventaris', 'coas' => ['601', '602', '603'], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '', 'description' => '    2. Pemulihan Penurunan Nilai', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4202010000', 'description' => '        a. Aset Tetap dan Inventaris', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4202030000', 'description' => '        b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4204000000', 'description' => '    4. Bunga Antarkantor', 'coas' => ['604'], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4205000000', 'description' => '    5. Selisih Kurs', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_income'],
                ['pos' => '4299000000', 'description' => '    6. Lainnya', 'coas' => ['690'], 'is_total' => false, 'group' => 'non_operating_income'],

                ['pos' => '5200000000', 'description' => 'Beban Nonoperasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_expense'],
                ['pos' => '', 'description' => '    1. Kerugian Penjualan/Kehilangan', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5201010000', 'description' => '        Aset Tetap dan Inventaris', 'coas' => ['701', '702', '703'], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '', 'description' => '    2. Kerugian Penurunan Nilai', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5202010000', 'description' => '        a. Aset Tetap dan Inventaris', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5202030000', 'description' => '        b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5203000000', 'description' => '    3. Bunga Antarkantor', 'coas' => ['704'], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5204000000', 'description' => '    4. Selisih Kurs', 'coas' => [], 'is_total' => false, 'group' => 'non_operating_expense'],
                ['pos' => '5299000000', 'description' => '    5. Lainnya', 'coas' => ['790'], 'is_total' => false, 'group' => 'non_operating_expense'],

                ['pos' => '3104040200', 'description' => 'Laba (Rugi) Nonoperasional', 'coas' => [], 'is_total' => true, 'formula' => 'non_operating_profit'],
                ['pos' => '3104040300', 'description' => 'Laba (Rugi) Tahun Berjalan Sebelum Pajak', 'coas' => [], 'is_total' => true, 'formula' => 'profit_before_tax'],
            ],
        ],

        'tax_and_comprehensive' => [
            'label' => 'Pajak & Penghasilan Komprehensif Lain',
            'rows' => [
                ['pos' => '5300000000', 'description' => 'Taksiran Pajak Penghasilan', 'coas' => ['558'], 'is_total' => false, 'group' => 'tax_expense'],
                ['pos' => '4400000000', 'description' => 'Pendapatan Pajak Tangguhan', 'coas' => [], 'is_total' => false, 'group' => 'deferred_tax_income'],
                ['pos' => '5400000000', 'description' => 'Beban Pajak Tangguhan', 'coas' => [], 'is_total' => false, 'group' => 'deferred_tax_expense'],
                ['pos' => '3104040400', 'description' => 'Jumlah Laba (Rugi) Tahun Berjalan', 'coas' => [], 'is_total' => true, 'formula' => 'current_year_profit'],

                ['pos' => '', 'description' => 'Penghasilan Komprehensif Lain', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '', 'description' => '    1. Tidak Akan Direklasifikasi ke Laba Rugi', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7101010000', 'description' => '        a. Keuntungan Revaluasi Aset Tetap', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7101990000', 'description' => '        b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7101980000', 'description' => '        c. Pajak Penghasilan Terkait', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '', 'description' => '    2. Akan Direklasifikasikan ke Laba Rugi', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102010000', 'description' => '        a. Keuntungan (Kerugian) dan Perubahan Nilai Aset Keuangan Dalam Kelompok Tersedia untuk Dijual', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102990000', 'description' => '        b. Lainnya', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '7102980000', 'description' => '        c. Pajak Penghasilan Terkait', 'coas' => [], 'is_total' => false, 'group' => 'other_comprehensive_income'],
                ['pos' => '3104040500', 'description' => 'Penghasilan Komprehensif Lain Setelah Pajak', 'coas' => [], 'is_total' => true, 'formula' => 'other_comprehensive_income'],
                ['pos' => '3104040600', 'description' => 'Total Laba (Rugi) Komprehensif Tahun Berjalan', 'coas' => [], 'is_total' => true, 'formula' => 'comprehensive_profit'],
            ],
        ],
    ],
];
